version: "3.9"

services:
  adservice-backend:
    image: adservice-backend
    container_name: adservice-backend
    restart: unless-stopped
    depends_on:
      database:
        condition: service_completed_successfully
    networks:
      - database_network
    ports:
      - "8080:8080"
  database:
    image: mysql:8.0.34
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: "services"
      MYSQL_ROOT_PASSWORD: "0000"
    networks:
      - database_network
    ports:
      - "3306:3306"

networks:
  database_network:
    name: database_network
    driver: bridge